### ISSUE TITLE
error: expected identifier

### ISSUE THREAD

**Issue by zeekay18** [amykyta3/speedy-antlr-example#1]
Hi,

I'm having the following error below when trying to run the setup.py file to build the c++ module

**OS: Linux Ubuntu**

Thank you

```
cpp_src/PlSqlLexer.h:211:5: error: expected identifier before ‘(’ token
     NAN = 881, NANVL = 882, NATIONAL = 883, NATIVE_FULL_OUTER_JOIN = 884,
     ^
cpp_src/PlSqlLexer.h:211:5: error: expected ‘}’ before ‘(’ token
cpp_src/PlSqlLexer.h:211:5: error: expected identifier before string constant
     NAN = 881, NANVL = 882, NATIONAL = 883, NATIVE_FULL_OUTER_JOIN = 884,
     ^

```

**Comment by amykyta3** [comment]
Hard to tell what is going on. Could you share your PlSql grammar file?

**Comment by zeekay18** [comment]
Hi,

Thank you. This is the grammar file i'm using [https://github.com/antlr/grammars-v4/tree/master/sql/plsql](https://github.com/antlr/grammars-v4/tree/master/sql/plsql)

**Comment by amykyta3** [comment]
I tried on my end (also Ubuntu) but could not reproduce the issue.
Did you make changes to the `PlSqlLexer.h` file? Mine seemed to compile without issues.

**Comment by zeekay18** [comment]
Hi, Thanks for your reply. I didn't make changes to the `PlSqlLexer.h` file.

Which changes should I make to the file?

**Comment by amykyta3** [comment]
I did not need to make any changes to the file.
Make sure you have also downloaded the plsql extension header files since the lexer requires them: https://github.com/antlr/grammars-v4/tree/master/sql/plsql/Cpp

Then in your setup.py, make sure these files are visible in the include path.
