### ISSUE TITLE
error with running the example

### ISSUE THREAD

**Issue by SmzAmir** [amykyta3/speedy-antlr-example#2]
thanks for the great work! I am trying to run your example. I installed the setup and run the run_example.py and it gives me this error:

`NameError: name 'sa_mygrammar_cpp_parser' is not defined`

it also mentioned that "Using Python implementation of parser"

I guess this issue is related to cpp import of the parser

**Comment by amykyta3** [comment]
Could you provide more details on what you tried? What commands did you run to install?

Depending on the python version you're using, you may want to upgrade pip, setuptools and wheel. Here is an example using a virtual environment:
```bash
# launch virtual environment
python3 -m venv my_venv
source my_venv/bin/activate

# Upgrade some things:
python3 -m pip install -U setuptools wheel pip

# Run install
cd speedy-antlr-example
python3 -m pip install .
./run_example.py
```

**Comment by SmzAmir** [comment]
I am using PyCharm so first I tried:
`pip install .`

Then:
`python run_example.py`

`
Using Python implementation of parser
([] ([10] ([2 10] ([2 2 10] ([21 2 2 10] ([43 21 2 2 10] 1))) + ([31 2 10] ([21 31 2 10] ([43 21 31 2 10] 2)))) + ([31 10] ([2 31 10] ([2 2 31 10] ([21 2 2 31 10] ([43 21
2 2 31 10] 3))) * ([28 2 31 10] ([21 28 2 31 10] ([43 21 28 2 31 10] 4)))) / ([28 31 10] ([21 28 31 10] ([43 21 28 31 10] 5))))) ; <EOF>)
Traceback (most recent call last):
  File "run_example.py", line 6, in <module>
    spam.benchmark("input_file.txt", 1000)
  File "F:\cc\ANTLR\speedy-antlr-example-master\env\lib\site-packages\spam\benchmark.py", line 10, in benchmark
    cpp_elapsed = timeit.timeit(lambda: sa_mygrammar._cpp_parse(antlr4.FileStream(input_file), "root"), number=count)
  File "C:\Users\****\AppData\Local\Programs\Python\Python38\lib\timeit.py", line 232, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)
  File "C:\Users\****\AppData\Local\Programs\Python\Python38\lib\timeit.py", line 176, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "F:\cc\ANTLR\speedy-antlr-example-master\env\lib\site-packages\spam\benchmark.py", line 10, in <lambda>
    cpp_elapsed = timeit.timeit(lambda: sa_mygrammar._cpp_parse(antlr4.FileStream(input_file), "root"), number=count)
  File "F:\cc\ANTLR\speedy-antlr-example-master\env\lib\site-packages\spam\parser\sa_mygrammar.py", line 105, in _cpp_parse
    return sa_mygrammar_cpp_parser.do_parse(MyGrammarParser, stream, entry_rule_name, sa_err_listener)
NameError: name 'sa_mygrammar_cpp_parser' is not defined
`

In the sa_mygrammar.py file where the sa_mygrammar_cpp_parser is imported. It is possible due to this since this is a CPP code,
 not a python module?

`
try:
    from . import sa_mygrammar_cpp_parser

except ImportError:
    USE_CPP_IMPLEMENTATION = False
`

**Comment by SmzAmir** [comment]
> I am using PyCharm so first I tried:
> `pip install .`
> 
> Then:
> `python run_example.py`
> 
> `Using Python implementation of parser ([] ([10] ([2 10] ([2 2 10] ([21 2 2 10] ([43 21 2 2 10] 1))) + ([31 2 10] ([21 31 2 10] ([43 21 31 2 10] 2)))) + ([31 10] ([2 31 10] ([2 2 31 10] ([21 2 2 31 10] ([43 21 2 2 31 10] 3))) * ([28 2 31 10] ([21 28 2 31 10] ([43 21 28 2 31 10] 4)))) / ([28 31 10] ([21 28 31 10] ([43 21 28 31 10] 5))))) ; <EOF>) Traceback (most recent call last): File "run_example.py", line 6, in <module> spam.benchmark("input_file.txt", 1000) File "F:\cc\ANTLR\speedy-antlr-example-master\env\lib\site-packages\spam\benchmark.py", line 10, in benchmark cpp_elapsed = timeit.timeit(lambda: sa_mygrammar._cpp_parse(antlr4.FileStream(input_file), "root"), number=count) File "C:\Users\****\AppData\Local\Programs\Python\Python38\lib\timeit.py", line 232, in timeit return Timer(stmt, setup, timer, globals).timeit(number) File "C:\Users\****\AppData\Local\Programs\Python\Python38\lib\timeit.py", line 176, in timeit timing = self.inner(it, self.timer) File "<timeit-src>", line 6, in inner File "F:\cc\ANTLR\speedy-antlr-example-master\env\lib\site-packages\spam\benchmark.py", line 10, in <lambda> cpp_elapsed = timeit.timeit(lambda: sa_mygrammar._cpp_parse(antlr4.FileStream(input_file), "root"), number=count) File "F:\cc\ANTLR\speedy-antlr-example-master\env\lib\site-packages\spam\parser\sa_mygrammar.py", line 105, in _cpp_parse return sa_mygrammar_cpp_parser.do_parse(MyGrammarParser, stream, entry_rule_name, sa_err_listener) NameError: name 'sa_mygrammar_cpp_parser' is not defined`
> 
> In the sa_mygrammar.py file where the sa_mygrammar_cpp_parser is imported. It is possible due to this since this is a CPP code,
> not a python module?
> 
> `
> try:
> from . import sa_mygrammar_cpp_parser
> 
> except ImportError:
> USE_CPP_IMPLEMENTATION = False
> `

I think I found the issue, I run the code on Windows 64-bit OS and I believe the `setup.py` is not compatible with this OS. I tried the same process on Linux and it worked. Note that the processing time took much longer on Linux so some steps might cause issue on Windows.

**Comment by amykyta3** [comment]
Yep! I was just going to point that out.
It should be compatible, but you will need to install the Microsoft Visual C++ compiler.

If you plan to create and deploy your own package to PyPi (or similar), I'd recommend using a build server that will compile the binary distributions for you. This removes the need for your users to install Microsoft's compiler. It also makes installation faster for Linux, since the user doesn't have to compile everything from source.

See the example config file I created for [Travis CI](travis-ci.org) here: https://github.com/amykyta3/speedy-antlr-example/blob/master/.travis.yml
It uses [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) to automate the creation of binary wheels for all compatible platforms.

**Comment by amykyta3** [comment]
Here is an example of one of my other projects that uses this method. Every time I publish a release, these wheels are built and deployed automatically for all active Python versions, and all supported OS: https://pypi.org/project/systemrdl-compiler/#files
It would be very tedious to do this manually :smile:

**Comment by SmzAmir** [comment]
Awesome! Thank you very much for your information and your support, I will definitely keep your suggestion in mind.
I confirm that the file is working as expected.

**Comment by Lynn09** [comment]
After I switch to Linux enviornment, I still got the sa_mygrammar_cpp_parser is not defined error... Should I build the ANTLR runtime or should I write any makefile to build the CPP code to make it work? I am new to CPP..

**Comment by Lynn09** [comment]
Thanks for the great tool! I am trying to speed up the PHP grammar parser using the speedy-antlr. But when I replace the original g4 files to my own g4 files which are separate lexer and parser I had this issue:
```
(my_venv) [root@ops-server speedy-antlr-example-master]# ./run_example.py 
Traceback (most recent call last):
  File "./run_example.py", line 6, in <module>
    spam.benchmark()
  File "/opt/speedy-antlr-example-master/my_venv/lib/python3.6/site-packages/spam/benchmark.py", line 13, in benchmark
    cpp_elapsed = timeit.timeit(lambda: sa_php._cpp_parse(input, "phpBlock"), number=count)
  File "/opt/anaconda3-5.2/lib/python3.6/timeit.py", line 233, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)
  File "/opt/anaconda3-5.2/lib/python3.6/timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "/opt/speedy-antlr-example-master/my_venv/lib/python3.6/site-packages/spam/benchmark.py", line 13, in <lambda>
    cpp_elapsed = timeit.timeit(lambda: sa_php._cpp_parse(input, "phpBlock"), number=count)
  File "/opt/speedy-antlr-example-master/my_venv/lib/python3.6/site-packages/spam/parser/sa_php.py", line 105, in _cpp_parse
    return sa_php_cpp_parser.do_parse(PhpParser, stream, entry_rule_name, sa_err_listener)
NameError: name 'sa_php_cpp_parser' is not defined
```
Could you give me some hints about what happen? I have change the module name in the setup.py but it didn't work...
